[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scPerturbEval"
version = "0.1.0"
description = "Single-cell perturbation evaluation utilities"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "numpy",
  "pandas",
  "scipy",
  "scikit-learn",
  "anndata",
  "scanpy",
  "pertpy==1.0.6",
  "gseapy",
  "torch",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
